server:
    port: 8080
    ssl:
        enabled: true
        key-store: classpath:keystore.p12
        key-store-type: PKCS12
        key-store-password: stamptourpkcs
    servlet:
        session:
            timeout: 1d
            cookie:
                name: JSESSIONID
                path: /
                http-only: false
                secure: true
                same-site: none


spring:
    application:
        name: finalStamp
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://ls-7d364c1e0c0dbf6ea580a4a1b4db9e2a1b7625bb.c76ie4socr1d.ap-northeast-2.rds.amazonaws.com:3306/stamptour?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: dbmasteruser
        password: test1234
    jpa:
        properties:
            hibernate.transaction.jta.platform: ""
        hibernate:
            ddl-auto: update
        show-sql: true
        open-in-view: false
    jackson:
        time-zone: Asia/Seoul

